// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domains} from '../models';

export function Chat(arg1:string):Promise<string>;

export function GetContexts():Promise<Array<domains.FileNodeDomain>>;

export function SelectDirectory(arg1:string):Promise<void>;
